---
- name: Update the package index
  apt:
    update_cache: yes

- name: Install required packages for database server
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - openssh-server
    - sudo
    - python3
    - python3-pip
    - python3-venv
    - mariadb-server
    - pkg-config
    - default-libmysqlclient-dev
  tags: db_packages

- name: Create a virtual environment for Python packages
  command: python3 -m venv /opt/python-venv
  args:
    creates: /opt/python-venv
  tags: venv

- name: Set the Python interpreter for Ansible
  set_fact:
    ansible_python_interpreter: /opt/python-venv/bin/python

- name: Install mysqlclient in the virtual environment
  command: /opt/python-venv/bin/pip install mysqlclient
  tags: mysqlclient_install

- name: Ensure MariaDB is running
  service:
    name: mariadb
    state: started
    enabled: true
  tags: mariadb

- name: Create MySQL database
  mysql_db:
    name: "{{ db_name }}"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: yes
  tags: mariadb

- name: Create MySQL user and grant privileges securely
  mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    host: '{{ db_server_internal_ip }}'
    priv: "{{ db_name }}.*:ALL"
    state: present
    login_user: root
    login_password: "{{ mysql_root_password }}"
  become: yes
  tags: mariadb

- name: Create employees table in the database securely
  mysql_query:
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_host: "{{ db_server_internal_ip }}"
    login_db: "{{ db_name }}"
    query: >
      CREATE TABLE IF NOT EXISTS employees (
        id INT AUTO_INCREMENT PRIMARY KEY,
        name VARCHAR(100),
        position VARCHAR(100),
        salary DECIMAL(10, 2)
      );
  tags: mariadb

- name: Insert sample data into employees table
  mysql_query:
    login_user: "{{ db_user }}"
    login_password: "{{ db_password }}"
    login_host: "{{ db_server_internal_ip }}"
    login_db: "{{ db_name }}"
    query: >
      INSERT INTO employees (name, position, salary)
      VALUES
        ('John Doe', 'Engineer', 70000.00),
        ('Jane Smith', 'Manager', 90000.00);
  tags: mariadb

- name: Configure MariaDB to listen only on the internal IP address
  lineinfile:
    path: /etc/mysql/mariadb.conf.d/50-server.cnf
    regexp: '^bind-address'
    line: 'bind-address = {{ db_server_internal_ip }}'
    state: present
  notify: Restart MariaDB
  tags: mariadb

- name: Ensure the firewall is configured to allow only internal traffic on port 3306
  ufw:
    rule: allow
    port: '3306'
    proto: tcp
    src: "{{ internal_network_cidr }}"
  become: yes
  tags: firewall

- name: Enable UFW firewall
  ufw:
    state: enabled
    policy: deny
  become: yes
  tags: firewall

# Handlers
- name: Restart MariaDB
  service:
    name: mariadb
    state: restarted
  become: yes
  tags: mariadb
